config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :movies, :favorites
  root to: 'movies#index'
  post '/favorites', to: 'favorites#create', as: 'add_favorite'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :read, Favorite

    can [:create, :update, :destroy], Favorite do |favorite|
      favorite.user == user
    end
  end
end



    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies, through: :favorites

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "Access denied!"
    flash.keep(:notice)
    redirect_to root_url
  end

  include CanCan::ControllerAdditions
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource  only: [:new, :create, :destroy]


    def index
        @favorites = Favorite.all
    end

    def new
        @favorite = Favorite.new
    end

    def create
        @favorite = Favorite.create movie_params
        redirect_to movie_path(@movie)
    end

    def destroy
        @favorite = Favorite.find(params[:id])
        @favorite.destroy
        redirect_to movies_path
    end

    private
    def movie_params
        params.require(:movie).permit(:title, :year, :genre, :synopsis, :picture)
    end

    def fav_params
      fav = params.require(:user).permit(:username)
      user_id = { user_id: current_user.id }
      fav.merge(user_id)
    end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def index
        @movies = Movie.all
    end

    def new
        @movie = Movie.new
    end

    def show
        @movie = Movie.find(params[:id])
    end

    def create
        @movie = Movie.create movie_params
        redirect_to movie_path(@movie)
    end

    def edit
        @movie = Movie.find(params[:id])
    end

    def update
        @movie = Movie.find(params[:id])
        @movie.update movie_params
        redirect_to movie_path(@movie)
    end

    def destroy
        @movie = Movie.find(params[:id])
        @movie.destroy
        redirect_to movies_path
    end

    private
    def movie_params
        params.require(:movie).permit(:title, :year, :genre, :synopsis, :picture)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/favorites/index.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <span><%= link_to "Logout", destroy_user_session_path, method: :delete %><span> |
  <span><%= link_to  "Home", movies_path %></span>
<% else %>
  <span><%= link_to "Sign up", new_user_registration_path %> </span> |
  <span><%= link_to "Login", new_user_session_path  %> </span> | 
  <span><%= link_to  "Home", movies_path %></span> 
<% end %>

<h1>favorites list</h1>
<ul>
  <% @favorites.each do |favorite| %>
    <li>
      <p><%= favorite.user_id %><?p>
    </li>
  <% end %>
</ul>

app/views/favorites/index2.html.erb
 <% if can? :create, favorite %>
  <td><%= link_to 'Edit', new_favorite_path(favorite) %></td>
<% end %>
      
<% if can? :destroy, favorite %>
  <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Amazing Movie App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <span><%= link_to "Logout", destroy_user_session_path, method: :delete %><span> |
  <span><%= link_to "Favorites", favorites_path  %></span> |
  <span><%= link_to  "Home", movies_path %></span> 
<% else %>
  <span><%= link_to "Sign up", new_user_registration_path %> </span> |
  <span><%= link_to "Login", new_user_session_path  %> </span> | 
  <span><%= link_to "Favorites", favorites_path  %></span> | 
  <span><%= link_to  "Home", movies_path %></span> 

<% end %>

<div class="movie">
<h1>Edit This Movie</h1>

<%= form_for @movie do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :genre %>:
  <%= f.text_field :genre %><br />

  <%= f.label :year %>:
  <%= f.text_field :year %><br />

  <%= f.label :synopsis %>: </br>
  <%= f.text_area :synopsis %><br />

  <%= f.label :picture %>:
  <%= f.text_field :picture %><br />

  <%= f.submit %>
<% end %>
</div>

app/views/movies/index.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <span><%= link_to "Logout", destroy_user_session_path, method: :delete %><span> |
  <span><%= link_to "Favorites", favorites_path  %></span>
<% else %>
  <span><%= link_to "Sign up", new_user_registration_path %> </span> |
  <span><%= link_to "Login", new_user_session_path  %> </span> | 
  <span><%= link_to "Favorites", favorites_path  %></span> 
<% end %>

<div class="movie">
<h1>Movie List</h1>
<ul>
  <% @movies.each do |movie| %>
    <li>
      <%= link_to movie.title, movie_path(movie) %>
    </li>
  <% end %>
</ul>

<div>
<%= link_to  "add new movie", new_movie_path %>
</div>
</div>

app/views/movies/new.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <span><%= link_to "Logout", destroy_user_session_path, method: :delete %><span> |
  <span><%= link_to "Favorites", favorites_path  %></span> |
  <span><%= link_to  "Home", movies_path %></span> 
<% else %>
  <span><%= link_to "Sign up", new_user_registration_path %> </span> |
  <span><%= link_to "Login", new_user_session_path  %> </span> | 
  <span><%= link_to "Favorites", favorites_path  %></span> |
  <span><%= link_to  "Home", movies_path %></span> 
<% end %>

<div class="movie"
<h1>Add a New Movie</h1>


<%= form_for @movie do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :genre %>:
  <%= f.text_field :genre %><br />

  <%= f.label :year %>:
  <%= f.text_field :year %><br />

  <%= f.label :synopsis %>:</br>
  <%= f.text_area :synopsis %><br />

  <%= f.label :picture %>:
  <%= f.text_field :picture %><br />

  <%= f.submit %>
<% end %>
</div>

app/views/movies/show.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <span><%= link_to "Logout", destroy_user_session_path, method: :delete %><span> |
  <span><%= link_to "Favorites", favorites_path  %></span> |
  <span><%= link_to  "Home", movies_path %></span> 
<% else %>
  <span><%= link_to "Sign up", new_user_registration_path %> </span> |
  <span><%= link_to "Login", new_user_session_path  %> </span> | 
  <span><%= link_to "Favorites", favorites_path  %></span> |
  <span><%= link_to  "Home", movies_path %></span> 
<% end %>

<div class="movie">
<h1><%= @movie.title %></h1>

<p>genre: <%= @movie.genre %></p>
<p>year: <%= @movie.year %></p>
<p>synopsis: <%= @movie.synopsis %></p>
<%= image_tag @movie.picture %></br>

<div>
    <div> <%= button_to @favorite, add_favorite_path(@favorite), method: :post%></div>
    <div> <%= link_to  "edit", edit_movie_path %> </div>
    <div><%= form_for @movie, method: :delete do |f| %>
        <%= f.submit "delete", class: 'delete' %>
    <% end %></div>
</div>
</div>